spring.application.name=api-gateway
server.port=8088
order.service.url=${ORDER_SERVICE_URL:http://localhost:8082}
customer.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8080}
restaurant.service.url=${RESTAURANT_SERVICE_URL:http://localhost:8081}
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console
